---
- name: Install Redis Server
  hosts: server01
  become: true
  become_user: root
  tasks:
    - name: Install Redis dependencies
      # apt:
      #   name: "{{ item }}"
      #   state: present
      # loop:
      #   - update
      #   - build-essential
      #   - tcl
      shell: apt update && apt install -y build-essential tcl python3-pip && pip3 install redis

      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

    - name: Check Redis Status
      shell: systemctl status redis --no-pager
      register: redis_status
      ignore_errors: true

    - name: Download and extract Redis source code
      get_url:
        url: "http://download.redis.io/releases/redis-6.2.5.tar.gz"
        dest: "/tmp/redis.tar.gz"
      #delegate_to: localhost
      when: redis_status.rc != 0

    - name: Extract Redis source code
      unarchive:
        src: "/tmp/redis.tar.gz"
        dest: "/tmp"
        remote_src: yes
      when: redis_status.rc != 0

    - name: Compile and install Redis
      shell: |
        cd /tmp/redis-6.2.5
        make
        make install
      args:
        executable: /bin/bash
      when: redis_status.rc != 0

    - name: Configure Redis
      template:
        src: redis.conf
        dest: /etc/redis.conf
      when: redis_status.rc != 0
      notify: Restart Redis

    - name: Create Redis systemd service
      template:
        src: redis.service
        dest: /etc/systemd/system/redis.service
      when: redis_status.rc != 0
      notify: Restart Redis

    - name: Start Redis service
      systemd:
        name: redis
        state: started
        enabled: yes
      when: redis_status.rc != 0

  handlers:
    - name: Restart Redis
      systemd:
        name: redis
        state: restarted
