---
- name: Play with_items
  hosts: server01
  gather_facts: true
  become_user: root
  become: true
  tasks:
    - name: copy files
      copy:
        src: "{{item}}"
        dest: /var/www/html/{{item}}
        owner: root
        group: root
        mode: "0755"
      with_items:
        - contact.html
        - test.js
        - test_1.css
