---
- name: Play For Creating Multiple Users
  hosts: server01
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - name: Create Users
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        groups: "{{ item.groups }}"
      with_items:
        - { name: testuser1, uid: 2001, groups: "ubuntu" }
        - { name: testuser2, uid: 2002, groups: "admin" }
        - { name: testuser3, uid: 2003, groups: "users" }
